### ISSUE TITLE
error styalising

### ISSUE THREAD

**Issue by CJHFUTURE** [benbenlijie/style_swap_tensorflow#5]
Hi any ideas on this error?

paperspace@psfzcd80u:~$ cd '/home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master' 
paperspace@psfzcd80u:~/Desktop/STRANSFER/style_swap_tensorflow-master$ python main.py -c config/example.json -s --content /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/images/content/gentlecat.png --style /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/images/style/9EhJC.jpg
/home/paperspace/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
Tensor("unstack:0", shape=(3, 3, 256, 441), dtype=float32)
WARNING:tensorflow:From /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/models/style_swap_model.py:126: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
INFO:tensorflow:Use pretrained model vgg_16
WARNING:tensorflow:Variable inverse_net/conv1/Conv/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/conv1/Conv/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual1/Repeat/convolution_1/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual1/Repeat/convolution_1/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual1/Repeat/convolution_2/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual1/Repeat/convolution_2/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual2/Repeat/convolution_1/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual2/Repeat/convolution_1/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual2/Repeat/convolution_2/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual2/Repeat/convolution_2/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual3/Repeat/convolution_1/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual3/Repeat/convolution_1/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual3/Repeat/convolution_2/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/residual3/Repeat/convolution_2/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/deconv1/Conv/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/deconv1/Conv/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/deconv2/Conv/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/deconv2/Conv/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/conv2/Conv/weights missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
WARNING:tensorflow:Variable inverse_net/conv2/Conv/biases missing in checkpoint /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
2018-09-02 06:31:26.888411: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-02 06:31:26.888872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: Quadro P5000 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:00:05.0
totalMemory: 15.89GiB freeMemory: 15.33GiB
2018-09-02 06:31:26.888905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-09-02 06:31:27.282016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-02 06:31:27.282087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-09-02 06:31:27.282110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-09-02 06:31:27.282520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14862 MB memory) -> physical GPU (device: 0, name: Quadro P5000, pci bus id: 0000:00:05.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/pretrained/vgg_16.ckpt
experiments/style_swap/checkpoint
Traceback (most recent call last):
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value inverse_net/residual3/Repeat/convolution_1/weights
	 [[Node: inverse_net/residual3/Repeat/convolution_1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@inverse_net/residual3/Repeat/convolution_1/weights"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](inverse_net/residual3/Repeat/convolution_1/weights)]]
	 [[Node: Squeeze_2/_115 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1964_Squeeze_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main()
  File "main.py", line 83, in main
    evaluate(config, args.content, args.style)
  File "main.py", line 53, in evaluate
    save(stylize, s_name)
  File "main.py", line 27, in save
    save_image(stylize_fn(ci), "{}/{}_{}.jpg".format(save_folder, c_name, s_name))
  File "main.py", line 48, in stylize
    model.input_image: origin, model.style_image: si,
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value inverse_net/residual3/Repeat/convolution_1/weights
	 [[Node: inverse_net/residual3/Repeat/convolution_1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@inverse_net/residual3/Repeat/convolution_1/weights"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](inverse_net/residual3/Repeat/convolution_1/weights)]]
	 [[Node: Squeeze_2/_115 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1964_Squeeze_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'inverse_net/residual3/Repeat/convolution_1/weights/read', defined at:
  File "main.py", line 89, in <module>
    main()
  File "main.py", line 83, in main
    evaluate(config, args.content, args.style)
  File "main.py", line 36, in evaluate
    model.init_evaluate_model()
  File "/home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/base/base_model.py", line 19, in init_evaluate_model
    self._build_evaluate_model()
  File "/home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/models/style_swap_model.py", line 58, in _build_evaluate_model
    self.generated = self._inverse_net(self.swaped_tensor)
  File "/home/paperspace/Desktop/STRANSFER/style_swap_tensorflow-master/models/style_swap_model.py", line 155, in _inverse_net
    weights_regularizer=slim.l2_regularizer(self.config.weight_regulation_scale))
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2467, in repeat
    outputs = layer(outputs, *args, **kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1049, in convolution
    outputs = layer.apply(inputs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 825, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    self.build(input_shapes)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 144, in build
    dtype=self.dtype)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 546, in add_variable
    partitioner=partitioner)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpointable.py", line 415, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1297, in get_variable
    constraint=constraint)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1093, in get_variable
    constraint=constraint)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 431, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1611, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1602, in _model_variable_getter
    use_resource=use_resource)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 291, in model_variable
    use_resource=use_resource)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 246, in variable
    use_resource=use_resource)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 408, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 800, in _get_single_variable
    use_resource=use_resource)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2157, in variable
    use_resource=use_resource)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2147, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2130, in default_variable_creator
    constraint=constraint)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 391, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 142, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3053, in identity
    "Identity", input=input, name=name)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value inverse_net/residual3/Repeat/convolution_1/weights
	 [[Node: inverse_net/residual3/Repeat/convolution_1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@inverse_net/residual3/Repeat/convolution_1/weights"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](inverse_net/residual3/Repeat/convolution_1/weights)]]
	 [[Node: Squeeze_2/_115 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1964_Squeeze_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by fangzhiming** [comment]
I got the same issue!
